MINIFICPP-2344 Update version number to 1.0.0
apache/nifi-minifi-cpp pull request #1769
Opened 2024-04-25 11:14 UTC by lordgamez

https://issues.apache.org/jira/browse/MINIFICPP-2344

-----------------------
Thank you for submitting a contribution to Apache NiFi - MiNiFi C++.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

### For all changes:
- [ ] Is there a JIRA ticket associated with this PR? Is it referenced
     in the commit message?

- [ ] Does your PR title start with MINIFICPP-XXXX where XXXX is the JIRA number you are trying to resolve? Pay particular attention to the hyphen "-" character.

- [ ] Has your PR been rebased against the latest commit within the target branch (typically main)?

- [ ] Is your initial contribution a single, squashed commit?

### For code changes:
- [ ] If adding new dependencies to the code, are these dependencies licensed in a way that is compatible for inclusion under [ASF 2.0](http://www.apache.org/legal/resolved.html#category-a)?
- [ ] If applicable, have you updated the LICENSE file?
- [ ] If applicable, have you updated the NOTICE file?

### For documentation related changes:
- [ ] Have you ensured that format looks appropriate for the output in which it is rendered?

### Note:
Please ensure that once the PR is submitted, you check GitHub Actions CI results for build issues and submit an update to your PR as soon as possible.

2024-04-25 11:30 UTC, martinzink requested changes

2024-04-25 11:33 UTC, lordgamez commented on CMakeLists.txt
> +project(nifi-minifi-cpp VERSION 1.0.0)
Good catch, I updated the other occurrences as well in 9228ce5a6f3219d2e6b90429a2467c56e5f09051

2024-04-25 11:53 UTC, szaszm commented
It would be nice to be able to differentiate between this and future versions, like 1.0 proper, but I didn't find any way to convince CMake to add something other than a number at the end. Any ideas?

2024-04-25 12:06 UTC, lordgamez commented
> It would be nice to be able to differentiate between this and future versions, like 1.0 proper, but I didn't find any way to convince CMake to add something other than a number at the end. Any ideas?

Unfortunately I had the same problem, I didn't find any solution for it in CMake either. I was thinking we could keep the version 1.0.0 here and only tag it with the `-M1` suffix in the git tag and convenience binaries.

2024-04-30 08:28 UTC, szaszm approved these changes

2024-04-30 09:28 UTC, fgerlits approved these changes

2024-04-30 12:57 UTC, martinzink approved these changes

2024-04-30 14:07 UTC, closed without merging